title: Garfik Kotek
description: Ten kotek ma swoją własną stronę
social_link: ''
social_username: ''
github_repo: ''
github_username: michaumiau
theme_color: cyan
remote_theme: internet-de-france/swiss
baseurl: /garfi_kot
defaults:
  - scope:
      path: ''
      type: pages
    values:
      category_name: ''
  - scope:
      path: ''
      type: posts
    values:
      categories: ''
remote_theme_layouts:
  - ''
  - default
  - page
  - post
  - home
  - category_index
social_links:
  - twitter
  - instagram
  - medium
  - dribbble
theme_colors:
  - black
  - blue
  - gray
  - magenta
  - orange
  - red
  - white
  - yellow
